# Generated by Django 4.0.4 on 2022-05-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plagiat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(editable=False, max_length=200)),
                ('original_article_name', models.CharField(editable=False, max_length=200)),
                ('plagiat_article', models.CharField(editable=False, max_length=200)),
                ('original_article_link', models.URLField(editable=False)),
                ('plagiat_article_link', models.URLField(editable=False)),
                ('percent_of_plagiat', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Plagiat',
                'verbose_name_plural': 'Plagiat',
            },
        ),
    ]
