# Generated by Django 4.0.4 on 2022-05-01 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plagiat',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 1, 16, 58, 11, 599919), editable=False),
        ),
        migrations.AlterField(
            model_name='plagiat',
            name='plagiat_article',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='plagiat',
            name='plagiat_article_link',
            field=models.URLField(default='', editable=False),
        ),
    ]
