# Generated by Django 4.0.4 on 2022-05-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_plagiat_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plagiat',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
