# Generated by Django 4.0.4 on 2022-05-02 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_plagiat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('site_name', models.CharField(editable=False, max_length=200)),
                ('topic', models.CharField(editable=False, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='plagiat',
            name='request_data_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.requestdata'),
            preserve_default=False,
        ),
    ]
