# Generated by Django 4.0.4 on 2022-05-02 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_requestdata_plagiat_request_data_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plagiat',
            name='request_data_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.requestdata'),
        ),
    ]
