# Generated by Django 4.0.4 on 2022-05-02 12:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_plagiat_request_data_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdata',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
