# Generated by Django 4.0.4 on 2022-05-02 12:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_requestdata_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plagiat',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='plagiat',
            name='original_article_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='plagiat',
            name='original_article_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='plagiat',
            name='percent_of_plagiat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plagiat',
            name='plagiat_article',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='plagiat',
            name='plagiat_article_link',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='plagiat',
            name='topic',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='requestdata',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='requestdata',
            name='site_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='requestdata',
            name='topic',
            field=models.CharField(max_length=200),
        ),
    ]
