# Generated by Django 4.0.4 on 2022-05-02 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_plagiat_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plagiat',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='requestdata',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
