# Generated by Django 4.0.4 on 2022-05-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_plagiat_datetime_alter_requestdata_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdata',
            name='number_of_articles',
            field=models.IntegerField(default=100),
        ),
    ]
