# Generated by Django 4.0.4 on 2022-05-12 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_requestdata_number_of_articles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plagiat',
            options={'verbose_name': 'Plagiat'},
        ),
        migrations.RenameField(
            model_name='plagiat',
            old_name='original_article_link',
            new_name='article_link',
        ),
        migrations.RenameField(
            model_name='plagiat',
            old_name='original_article_name',
            new_name='article_name',
        ),
        migrations.RenameField(
            model_name='plagiat',
            old_name='plagiat_article_link',
            new_name='compared_article_link',
        ),
        migrations.RenameField(
            model_name='plagiat',
            old_name='plagiat_article',
            new_name='compared_article_name',
        ),
    ]
