# Generated by Django 4.0.4 on 2022-05-12 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_plagiat_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plagiat',
            old_name='request_data_id',
            new_name='request_data',
        ),
    ]
