# Generated by Django 4.0.4 on 2022-05-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_request_data_id_plagiat_request_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdata',
            name='number_of_articles',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
