# Generated by Django 4.0.4 on 2022-05-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_requestdata_number_of_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='plagiat',
            name='article_text',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.AddField(
            model_name='plagiat',
            name='compared_article_text',
            field=models.CharField(default='', max_length=1500),
        ),
    ]
