# Generated by Django 4.0.4 on 2022-05-31 14:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_plagiat_article_text_plagiat_compared_article_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plagiat',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='plagiat',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='requestdata',
            name='datetime',
        ),
        migrations.CreateModel(
            name='RequestDateTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('request_data', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.requestdata')),
            ],
        ),
    ]
