# Generated by Django 4.0.4 on 2022-05-31 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_plagiat_plagiarism'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plagiarism',
            options={'verbose_name': 'Plagiarism'},
        ),
        migrations.AlterField(
            model_name='requestdatetime',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='plagiarism',
            index=models.Index(fields=['percent_of_plagiat'], name='percent_of_plagiat_idx'),
        ),
        migrations.AddIndex(
            model_name='requestdata',
            index=models.Index(fields=['topic'], name='topic_idx'),
        ),
    ]
