# Generated by Django 4.0.4 on 2022-05-31 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_plagiarism_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestdatetime',
            options={'verbose_name': 'Plagiarism'},
        ),
        migrations.AlterField(
            model_name='requestdatetime',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddIndex(
            model_name='requestdatetime',
            index=models.Index(fields=['datetime'], name='datetime_idx'),
        ),
    ]
